import type { Category, FoodItem } from "./types"

export const categories: Category[] = [
  { id: "pizza", name: "Pizza" },
  { id: "burger", name: "Burgers" },
  { id: "pasta", name: "Pasta" },
  { id: "salad", name: "Salads" },
  { id: "dessert", name: "Desserts" },
  { id: "drink", name: "Drinks" },
  { id: "sides", name: "Sides" },
]

export const allItems: FoodItem[] = [
  {
    id: "1",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and basil",
    price: 12.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "pizza",
    vegetarian: true,
    popular: true,
  },
  {
    id: "2",
    name: "Pepperoni Pizza",
    description: "Pizza topped with pepperoni, cheese, and tomato sauce",
    price: 14.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "pizza",
    vegetarian: false,
    popular: true,
  },
  {
    id: "3",
    name: "Veggie Supreme Pizza",
    description: "Pizza loaded with bell peppers, onions, mushrooms, and olives",
    price: 13.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "pizza",
    vegetarian: true,
  },
  {
    id: "4",
    name: "BBQ Chicken Pizza",
    description: "Pizza with BBQ sauce, chicken, red onions, and cilantro",
    price: 15.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "pizza",
    vegetarian: false,
  },
  {
    id: "5",
    name: "Classic Cheeseburger",
    description: "Juicy beef patty with cheese, lettuce, tomato, and special sauce",
    price: 10.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "burger",
    vegetarian: false,
    popular: true,
  },
  {
    id: "6",
    name: "Veggie Burger",
    description: "Plant-based patty with lettuce, tomato, onion, and vegan mayo",
    price: 11.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "burger",
    vegetarian: true,
  },
  {
    id: "7",
    name: "Spaghetti Bolognese",
    description: "Spaghetti with rich meat sauce and parmesan cheese",
    price: 13.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "pasta",
    vegetarian: false,
  },
  {
    id: "8",
    name: "Fettuccine Alfredo",
    description: "Fettuccine pasta in creamy parmesan sauce",
    price: 12.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "pasta",
    vegetarian: true,
  },
  {
    id: "9",
    name: "Caesar Salad",
    description: "Romaine lettuce, croutons, parmesan cheese with Caesar dressing",
    price: 8.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "salad",
    vegetarian: true,
  },
  {
    id: "10",
    name: "Chocolate Brownie",
    description: "Warm chocolate brownie with vanilla ice cream",
    price: 6.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "dessert",
    vegetarian: true,
    popular: true,
  },
  {
    id: "11",
    name: "French Fries",
    description: "Crispy golden fries with ketchup",
    price: 4.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "sides",
    vegetarian: true,
  },
  {
    id: "12",
    name: "Soft Drink",
    description: "Choice of Coke, Sprite, or Fanta",
    price: 2.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "drink",
    vegetarian: true,
  },
]

export const featuredItems = allItems.filter((item) => item.popular)

